inherit_from: .rubocop_todo.yml

# 自動生成されたファイルを対象外にする
AllCops:
  TargetRubyVersion: 2.7.3
  Rails:
    Enabled: true
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

# 日本語コメントを許可。
Style/AsciiComments:
  Enabled: false

# 1つのブロックあたりの行数。テスト関連のコードは除外。
LMetrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'Guardfile'

# 1つのメソッドあたりの行数。テスト関連のコードは除外。
Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

# has_, is_, have_ など特定の文字列で始まるメソッド名。テストでは許可する。
Naming/PredicateName:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

# 1行あたりの文字数。テスト関連のコードは除外。
Layout/LineLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

# ドキュメントの付与がないことを許可。
Style/Documentation:
  Enabled: false

# 代入×関数呼び出し×制御構文の個数。
Metrics/AbcSize:
  Max: 21

# 括弧なしの場合のメソッドの関連性が曖昧か。テストは除外。
int/AmbiguousBlockAssociation:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
