version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - gem_modules:/app/vendor/bundle
      - node_modules:/app/node_modules
      - sockets:/app/tmp/sockets
      - public-data:/app/public
    environment:
      BUNDLE_APP_CONFIG: ./.bundle
      RAILS_ENV: production

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - sockets:/app/tmp/sockets
      - public-data:/app/public
    depends_on:
      - web

volumes:
  gem_modules:
  node_modules:
  sockets:
  public-data:
