# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: app
  password: password
  timeout: 5000
  port: 3306
  host: db

development:
  <<: *default
  database: mysql_development

test:
  <<: *default
  username: <%= ENV.fetch('TEST_USERNAME') { 'app' } %>
  password: <%= ENV.fetch('TEST_USERPASS') { 'password' } %>
  host: <%= ENV.fetch('TEST_DB_HOST') { 'test-db' } %>
  database: mysql_test
