# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 3306
  host: db

development:
  <<: *default
  username: <%= ENV.fetch('DEV_USERNAME') { 'app' } %>
  password: <%= ENV.fetch('DEV_USERPASS') { 'password' } %>
  database: <%= ENV.fetch('DEV_DATABASE') { 'mysql_development' } %>

test:
  <<: *default
  username: <%= ENV.fetch('TEST_USERNAME') { 'app' } %>
  password: <%= ENV.fetch('TEST_USERPASS') { 'passwrd' } %>
  database: <%= ENV.fetch('TEST_DATABASE') { 'mysql_test' } %>
  host: <%= ENV.fetch('TEST_DB_HOST') { 'test-db' } %>

production:
  <<: *default
  username: <%= ENV.fetch('PROD_USERNAME') { 'app' } %>
  password: <%= ENV.fetch('PROD_USERPASS') { 'password' } %>
  database: <%= ENV.fetch('PROD_DATABASE') { 'mysql_prod' } %>
